name: 'OpenAPI CLI Bundle'

description: >
  Bundle a multiple file OpenAPI spec into a single file using Redocly's openapi-cli

branding:
  icon: box
  color: green

inputs:
  base-spec:
    description: Path to the BASE OpenAPI specification file
    required: true

outputs:
  bundled-spec:
    description: Path to the output bundled OpenAPI specification file

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.base-spec }}
    - ${{ inputs.bundled-spec }}
